# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createSample.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Sample_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1325, 779)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 1281, 701))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infoWidget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.infoWidget.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.infoWidget.setObjectName("infoWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.infoWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 391, 344))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.NameEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.NameEdit.setObjectName("NameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.NameEdit)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.AgeEdit = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.AgeEdit.setObjectName("AgeEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.AgeEdit)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.MaleEdit = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.MaleEdit.setObjectName("MaleEdit")
        self.horizontalLayout_2.addWidget(self.MaleEdit)
        self.FemaleEdit = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.FemaleEdit.setObjectName("FemaleEdit")
        self.horizontalLayout_2.addWidget(self.FemaleEdit)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        # spacerItem = QtWidgets.QSpacerItem(20, 89, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.DiseaseDescEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.DiseaseDescEdit.setObjectName("DiseaseDescEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.DiseaseDescEdit)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spinBox = textSpinBox(self.verticalLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.RecorderEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.RecorderEdit.setObjectName("RecorderEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.RecorderEdit)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.LocateEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LocateEdit.setObjectName("LocateEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LocateEdit)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.RecPlanEdit = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.RecPlanEdit.setObjectName("RecPlanEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.RecPlanEdit)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.sentenceIdEdit = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sentenceIdEdit.setObjectName("sentenceIdEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sentenceIdEdit)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout.addWidget(self.infoWidget)
        self.visualDatWidget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.visualDatWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.visualDatWidget.setObjectName("visualDatWidget")
        self.horizontalLayout.addWidget(self.visualDatWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.infoWidget.setLayout(self.verticalLayout)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Thong tin nguoi benh"))
        self.label_4.setText(_translate("Dialog", "Họ tên người bệnh"))
        self.label_5.setText(_translate("Dialog", "Tuổi"))
        self.label_6.setText(_translate("Dialog", "Giới tính"))
        self.MaleEdit.setText(_translate("Dialog", "Nam"))
        self.FemaleEdit.setText(_translate("Dialog", "Nữ"))
        self.label_7.setText(_translate("Dialog", "Mô tả bệnh"))
        self.label_3.setText(_translate("Dialog", "Tình trạng bệnh"))
        self.label_8.setText(_translate("Dialog", "thong tin thu"))
        self.label_11.setText(_translate("Dialog", "Kỹ thuật viên"))
        self.label_12.setText(_translate("Dialog", "Địa điểm"))
        self.label_13.setText(_translate("Dialog", "Kịch bản"))
        self.label_21.setText(_translate("Dialog", "Câu trong kịch bản"))
        self.label_14.setText(_translate("Dialog", "Thời gian"))


class textSpinBox(QSpinBox):
    def __init__(self, parent=None):
        super(textSpinBox, self).__init__(parent)
        self.set_list_string()

    def set_list_string(self, strings=None):
        if strings is not None:
            self.list_text = strings
        else:
            self.list_text = ["Khỏe", "Bình thường", "Yếu"]
        self.setRange(0, len(self.list_text) - 1)

    def textFromValue(self, value):
        return self.list_text[value]

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
