# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test01.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from genUICreate import Ui_Form
import json
import random
import os 
import math
from utility import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(728, 563)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("my-beautiful-life-logo-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.abc = QtWidgets.QWidget(MainWindow)
        self.abc.setObjectName("abc")
        self.label = QtWidgets.QLabel(self.abc)
        self.label.setGeometry(QtCore.QRect(20, 80, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.abc)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 110, 701, 361))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.abc)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 480, 711, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.GoPageBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.GoPageBtn.setObjectName("GoPageBtn")
        self.horizontalLayout_3.addWidget(self.GoPageBtn)
        self.view1 = QtWidgets.QPushButton(self.abc)
        self.view1.setGeometry(QtCore.QRect(508, 132, 102, 31))
        self.view1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("editIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view1.setIcon(icon1)
        self.view1.setObjectName("view1")
        self.view1_2 = QtWidgets.QPushButton(self.abc)
        self.view1_2.setEnabled(True)
        self.view1_2.setGeometry(QtCore.QRect(508, 162, 102, 31))
        self.view1_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view1_2.setText("")
        self.view1_2.setIcon(icon1)
        self.view1_2.setObjectName("view1_2")
        self.view1_3 = QtWidgets.QPushButton(self.abc)
        self.view1_3.setGeometry(QtCore.QRect(508, 192, 102, 31))
        self.view1_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view1_3.setText("")
        self.view1_3.setIcon(icon1)
        self.view1_3.setObjectName("view1_3")
        self.view1_4 = QtWidgets.QPushButton(self.abc)
        self.view1_4.setGeometry(QtCore.QRect(508, 222, 102, 31))
        self.view1_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view1_4.setText("")
        self.view1_4.setIcon(icon1)
        self.view1_4.setObjectName("view1_4")
        self.view1_5 = QtWidgets.QPushButton(self.abc)
        self.view1_5.setGeometry(QtCore.QRect(508, 252, 102, 31))
        self.view1_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view1_5.setText("")
        self.view1_5.setIcon(icon1)
        self.view1_5.setObjectName("view1_5")
        self.view1_6 = QtWidgets.QPushButton(self.abc)
        self.view1_6.setGeometry(QtCore.QRect(508, 282, 102, 31))
        self.view1_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view1_6.setText("")
        self.view1_6.setIcon(icon1)
        self.view1_6.setObjectName("view1_6")
        self.view1_7 = QtWidgets.QPushButton(self.abc)
        self.view1_7.setGeometry(QtCore.QRect(508, 312, 102, 31))
        self.view1_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view1_7.setText("")
        self.view1_7.setIcon(icon1)
        self.view1_7.setObjectName("view1_7")
        self.view1_8 = QtWidgets.QPushButton(self.abc)
        self.view1_8.setGeometry(QtCore.QRect(508, 342, 102, 31))
        self.view1_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view1_8.setText("")
        self.view1_8.setIcon(icon1)
        self.view1_8.setObjectName("view1_8")
        self.view1_9 = QtWidgets.QPushButton(self.abc)
        self.view1_9.setGeometry(QtCore.QRect(508, 372, 102, 31))
        self.view1_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view1_9.setText("")
        self.view1_9.setIcon(icon1)
        self.view1_9.setObjectName("view1_9")
        self.view1_10 = QtWidgets.QPushButton(self.abc)
        self.view1_10.setGeometry(QtCore.QRect(508, 402, 102, 31))
        self.view1_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view1_10.setText("")
        self.view1_10.setIcon(icon1)
        self.view1_10.setObjectName("view1_10")
        self.delete1 = QtWidgets.QPushButton(self.abc)
        self.delete1.setGeometry(QtCore.QRect(609, 132, 102, 31))
        self.delete1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("deleteIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete1.setIcon(icon2)
        self.delete1.setObjectName("delete1")
        self.delete1_2 = QtWidgets.QPushButton(self.abc)
        self.delete1_2.setGeometry(QtCore.QRect(609, 162, 102, 31))
        self.delete1_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete1_2.setText("")
        self.delete1_2.setIcon(icon2)
        self.delete1_2.setObjectName("delete1_2")
        self.delete1_3 = QtWidgets.QPushButton(self.abc)
        self.delete1_3.setGeometry(QtCore.QRect(609, 192, 102, 31))
        self.delete1_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete1_3.setText("")
        self.delete1_3.setIcon(icon2)
        self.delete1_3.setObjectName("delete1_3")
        self.delete1_4 = QtWidgets.QPushButton(self.abc)
        self.delete1_4.setGeometry(QtCore.QRect(609, 222, 102, 31))
        self.delete1_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete1_4.setText("")
        self.delete1_4.setIcon(icon2)
        self.delete1_4.setObjectName("delete1_4")
        self.delete1_5 = QtWidgets.QPushButton(self.abc)
        self.delete1_5.setGeometry(QtCore.QRect(609, 252, 102, 31))
        self.delete1_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete1_5.setText("")
        self.delete1_5.setIcon(icon2)
        self.delete1_5.setObjectName("delete1_5")
        self.delete1_6 = QtWidgets.QPushButton(self.abc)
        self.delete1_6.setGeometry(QtCore.QRect(609, 282, 102, 31))
        self.delete1_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete1_6.setText("")
        self.delete1_6.setIcon(icon2)
        self.delete1_6.setObjectName("delete1_6")
        self.delete1_7 = QtWidgets.QPushButton(self.abc)
        self.delete1_7.setGeometry(QtCore.QRect(609, 312, 102, 31))
        self.delete1_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete1_7.setText("")
        self.delete1_7.setIcon(icon2)
        self.delete1_7.setObjectName("delete1_7")
        self.delete1_8 = QtWidgets.QPushButton(self.abc)
        self.delete1_8.setGeometry(QtCore.QRect(609, 342, 102, 31))
        self.delete1_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete1_8.setText("")
        self.delete1_8.setIcon(icon2)
        self.delete1_8.setObjectName("delete1_8")
        self.delete1_9 = QtWidgets.QPushButton(self.abc)
        self.delete1_9.setGeometry(QtCore.QRect(609, 372, 102, 31))
        self.delete1_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete1_9.setText("")
        self.delete1_9.setIcon(icon2)
        self.delete1_9.setObjectName("delete1_9")
        self.delete1_10 = QtWidgets.QPushButton(self.abc)
        self.delete1_10.setGeometry(QtCore.QRect(609, 402, 102, 31))
        self.delete1_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete1_10.setText("")
        self.delete1_10.setIcon(icon2)
        self.delete1_10.setObjectName("delete1_10")
        self.delete1_11 = QtWidgets.QPushButton(self.abc)
        self.delete1_11.setGeometry(QtCore.QRect(510, 440, 201, 31))
        self.delete1_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete1_11.setIcon(icon2)
        self.delete1_11.setObjectName("delete1_11")
        self.gridLayoutWidget = QtWidgets.QWidget(self.abc)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 701, 56))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Signal1 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.Signal1.setEnabled(False)
        self.Signal1.setStyleSheet("background-color: rgba(255,255,255,0);border: 0px;")
        self.Signal1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("redBtn.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("greenbt2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("greenbt2.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("redBtn.jpg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("redBtn.jpg"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.Signal1.setIcon(icon3)
        self.Signal1.setCheckable(True)
        self.Signal1.setChecked(True)
        self.Signal1.setObjectName("Signal1")
        self.gridLayout_2.addWidget(self.Signal1, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.Signal4 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.Signal4.setEnabled(False)
        self.Signal4.setStyleSheet("background-color: rgba(255,255,255,0);border: 0px;")
        self.Signal4.setText("")
        self.Signal4.setIcon(icon3)
        self.Signal4.setCheckable(True)
        self.Signal4.setChecked(True)
        self.Signal4.setObjectName("Signal4")
        self.gridLayout_2.addWidget(self.Signal4, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.Signal2 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.Signal2.setEnabled(False)
        self.Signal2.setStyleSheet("background-color: rgba(255,255,255,0);border: 0px;")
        self.Signal2.setText("")
        self.Signal2.setIcon(icon3)
        self.Signal2.setCheckable(True)
        self.Signal2.setChecked(True)
        self.Signal2.setObjectName("Signal2")
        self.gridLayout_2.addWidget(self.Signal2, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.Signal3 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.Signal3.setEnabled(False)
        self.Signal3.setStyleSheet("background-color: rgba(255,255,255,0);border: 0px;")
        self.Signal3.setText("")
        self.Signal3.setIcon(icon3)
        self.Signal3.setCheckable(True)
        self.Signal3.setChecked(True)
        self.Signal3.setObjectName("Signal3")
        self.gridLayout_2.addWidget(self.Signal3, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.Signal5 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.Signal5.setEnabled(False)
        self.Signal5.setStyleSheet("background-color: rgba(255,255,255,0);border: 0px;")
        self.Signal5.setText("")
        self.Signal5.setIcon(icon3)
        self.Signal5.setCheckable(True)
        self.Signal5.setChecked(True)
        self.Signal5.setObjectName("Signal5")
        self.gridLayout_2.addWidget(self.Signal5, 1, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.RecordingBtn = QtWidgets.QPushButton(self.abc)
        self.RecordingBtn.setGeometry(QtCore.QRect(590, 60, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RecordingBtn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("addIcn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RecordingBtn.setIcon(icon4)
        self.RecordingBtn.setIconSize(QtCore.QSize(24, 24))
        self.RecordingBtn.setObjectName("RecordingBtn")
        self.frame = QtWidgets.QFrame(self.abc)
        self.frame.setGeometry(QtCore.QRect(10, 0, 701, 31))
        self.frame.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.label.raise_()
        self.tableWidget.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.view1.raise_()
        self.view1_2.raise_()
        self.view1_3.raise_()
        self.view1_4.raise_()
        self.view1_5.raise_()
        self.view1_6.raise_()
        self.view1_7.raise_()
        self.view1_8.raise_()
        self.view1_9.raise_()
        self.view1_10.raise_()
        self.delete1.raise_()
        self.delete1_2.raise_()
        self.delete1_3.raise_()
        self.delete1_4.raise_()
        self.delete1_5.raise_()
        self.delete1_6.raise_()
        self.delete1_7.raise_()
        self.delete1_8.raise_()
        self.delete1_9.raise_()
        self.delete1_10.raise_()
        self.delete1_11.raise_()
        self.gridLayoutWidget.raise_()
        self.RecordingBtn.raise_()
        MainWindow.setCentralWidget(self.abc)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



        self.RecordingBtn.clicked.connect(self.recordingScreen)

        # data processes
        self.listViewBtn = [self.view1, self.view1_2, self.view1_3, self.view1_4, self.view1_5, self.view1_6, self.view1_7, self.view1_8
        , self.view1_9, self.view1_10]
        self.listDelBtn = [self.delete1, self.delete1_2, self.delete1_3, self.delete1_4, self.delete1_5, self.delete1_6, self.delete1_7
        , self.delete1_8, self.delete1_9, self.delete1_10]
        self.jsonFiles = readData()
        self.loadData2Table()


        # page move 
        self.GoPageBtn.clicked.connect(lambda: self.goPage(self.spinBox.value()))
        self.pushButton_6.clicked.connect(lambda: self.goPage(self.current_page-1))
        self.pushButton_7.clicked.connect(lambda: self.goPage(self.current_page+1))

        # delete btn

        self.delete1.clicked.connect(lambda: self.showChoosePopup("Do you want to delete: ", self.current_page * 10+0))
        self.delete1_2.clicked.connect(lambda: self.showChoosePopup("Do you want to delete: " , self.current_page * 10+1))
        self.delete1_3.clicked.connect(lambda: self.showChoosePopup("Do you want to delete: " , self.current_page * 10+2))
        self.delete1_4.clicked.connect(lambda: self.showChoosePopup("Do you want to delete: " , self.current_page * 10+3))
        self.delete1_5.clicked.connect(lambda: self.showChoosePopup("Do you want to delete: " , self.current_page * 10+4))
        self.delete1_6.clicked.connect(lambda: self.showChoosePopup("Do you want to delete: " , self.current_page * 10+5))
        self.delete1_7.clicked.connect(lambda: self.showChoosePopup("Do you want to delete: " , self.current_page * 10+6))
        self.delete1_8.clicked.connect(lambda: self.showChoosePopup("Do you want to delete: " , self.current_page * 10+7))
        self.delete1_9.clicked.connect(lambda: self.showChoosePopup("Do you want to delete: " , self.current_page * 10+8))
        self.delete1_10.clicked.connect(lambda: self.showChoosePopup("Do you want to delete: " , self.current_page * 10+9))

        # view btn
        self.view1.clicked.connect(lambda: self.viewFunction(self.current_page * 10+0))
        self.view1_2.clicked.connect(lambda: self.viewFunction(self.current_page * 10+1))
        self.view1_3.clicked.connect(lambda: self.viewFunction(self.current_page * 10+2))
        self.view1_4.clicked.connect(lambda: self.viewFunction(self.current_page * 10+3))
        self.view1_5.clicked.connect(lambda: self.viewFunction(self.current_page * 10+4))
        self.view1_6.clicked.connect(lambda: self.viewFunction(self.current_page * 10+5))
        self.view1_7.clicked.connect(lambda: self.viewFunction(self.current_page * 10+6))
        self.view1_8.clicked.connect(lambda: self.viewFunction(self.current_page * 10+7))
        self.view1_9.clicked.connect(lambda: self.viewFunction(self.current_page * 10+8))
        self.view1_10.clicked.connect(lambda: self.viewFunction(self.current_page * 10+9))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Danh sách bản ghi"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mã bản ghi"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Kịch bản"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Họ tên đối tượng"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Thời gian ghi"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Xem"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Xóa"))
        self.pushButton_6.setText(_translate("MainWindow", "previous page"))
        self.pushButton_7.setText(_translate("MainWindow", "next page"))
        self.GoPageBtn.setText(_translate("MainWindow", "Go"))
        self.delete1_11.setText(_translate("MainWindow", "Xóa toàn bộ ?"))
        self.label_5.setText(_translate("MainWindow", "CAM1"))
        self.label_2.setText(_translate("MainWindow", "Máy thu tín hiệu"))
        self.label_3.setText(_translate("MainWindow", "ET"))
        self.label_6.setText(_translate("MainWindow", "CAM1"))
        self.label_4.setText(_translate("MainWindow", "EEG"))
        self.RecordingBtn.setText(_translate("MainWindow", "Recording"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionClose.setText(_translate("MainWindow", "Close"))


    def loadData2Table(self):
        current_page = 0
        idxL = current_page * 10
        listShow = self.jsonFiles[idxL:idxL+10]
        # readJson
        self.listData = []
        for row, file in enumerate(listShow):
            with open(file) as json_file:
                data = json.load(json_file)
                self.listData.append(data)
            # print(data)
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(row + idxL)))
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(data['id'])))
            self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(str(data['recPlan'])))
            self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(data['name']))
            self.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(data['time']))
        if len(listShow) < 10:
            for row in range(len(listShow), 10):
                self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str('')))
                self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str('')))
                self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(str('')))
                self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(str('')))
                self.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(str('')))
                self.listViewBtn[row].setEnabled(False)
                self.listDelBtn[row].setEnabled(False)
        self.spinBox.setValue(0)
        numberPage = math.ceil(len(self.jsonFiles) / 10)
        self.spinBox.setMaximum(max(numberPage-1,0))
        self.current_page = 0


    def recordingScreen(self):
        self.Form = QtWidgets.QWidget()
        self.uiForm = Ui_Form()
        self.uiForm.setupUi(self.Form)
        self.uiForm.centerUI(self.Form)
        self.Form.show()
        self.uiForm.LoadBtn.clicked.connect(self.visualData)
        self.uiForm.SaveBtn.clicked.connect(self.createData)

    def visualData(self):
        self.uiForm.extendSize(self.Form)
        # **********************************Mr_HOA*******************************
        # load Data
        # **********************************Mr_HOA*******************************

        # create Gif
        EEGData = readFile("./exampleEEG")
        EEGData = EEGData.astype(float)
        EEGData = EEGData[3:17,:]
        self.uiForm.loadData(EEGData)
        self.uiForm.addGif(self.Form)
        self.uiForm.LoadBtn.setText("Reload")        

    def showErrorPopup(self, error):
        msg  = QtWidgets.QMessageBox()
        msg.setText(str(error))
        x = msg.exec_()

    def showChoosePopup(self, error, pos):
        msg  = QtWidgets.QMessageBox()
        msg.setText(str(error) + str(self.jsonFiles[pos]))
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok | QtWidgets.QMessageBox.Cancel)
        self.ChoosePopupParam = pos
        msg.buttonClicked.connect(self.choosedInMsgDelete)
        x = msg.exec_()
    
    def choosedInMsgDelete(self, i):
        if i.text() == "OK":
            self.delItem(self.ChoosePopupParam)


    def createData(self):
        name = self.uiForm.NameEdit.text()
        age = self.uiForm.AgeEdit.value()
        genderG = self.uiForm.FemaleEdit.isChecked()
        genderM = self.uiForm.MaleEdit.isChecked()
        patientDesc = self.uiForm.DiseaseDescEdit.toPlainText()
        recorder = self.uiForm.RecorderEdit.text()
        location = self.uiForm.LocateEdit.text()
        recPlan = self.uiForm.RecPlanEdit.value()
        timeTmp = self.uiForm.dateTimeEdit.dateTime()
        # dt.toString("dd.MM.yyyy hh:mm:ss.zzz"))
        time_string = timeTmp.toString(self.uiForm.dateTimeEdit.displayFormat())
        # check avalibale
        missingValue = False
        if name == '' or patientDesc == '' or recorder == '' or location == '':
            missingValue = True
        elif not genderG and not genderM : 
            missingValue = True
        elif age == 0 or recPlan == 0:
            missingValue = True
        if not missingValue:
            gender = "M"
            if genderG:
                gender = "Fm"
            # get ID 
            recordID = random.randint(1, 100)
            js = {
            'id': recordID,
            'name' : name, 
            'age' : age, 
            'gender': gender, 
            'patientDesc': patientDesc, 
            'recorder' : recorder, 
            'location' : location, 
            'recPlan' : recPlan, 
            'time' : time_string
            }
            fileName = './dataVIN/data' + str(recordID) + '.json'
            self.jsonFiles.append(fileName)
            with open(fileName, 'w') as outfile:
                json.dump(js, outfile)
            # print('success')
            self.Form.close()
            self.refreshPage(math.ceil(len(self.jsonFiles) / 10)-1)
        else:
            self.showErrorPopup("Please complete fully the form")

    def goPage(self, pos, noWarning = False):
        # print(pos)
        # print(self.current_page)

        numberPage = math.ceil(len(self.jsonFiles) / 10)
        # print(numberPage)
        if not noWarning:
            # print("not warning")
            if pos >= numberPage or pos < 0:
                self.showErrorPopup("Out of number page: " + str(pos))
                self.refreshPage(self.current_page)
            else:
                self.refreshPage(pos)
        else:
            if pos >= numberPage or pos < 0:
                self.refreshPage(self.current_page)
            else:
                self.refreshPage(pos)

    def refreshPage(self, pageNumInput):
        pageNum = max(pageNumInput, 0)
        idxL = pageNum * 10
        listShow = self.jsonFiles[idxL:idxL+10]
        # readJson
        self.listData = []
        for row, file in enumerate(listShow):
            with open(file) as json_file:
                data = json.load(json_file)
                self.listData.append(data)
            # print(data)
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(row + idxL)))
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(data['id'])))
            self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(str(data['recPlan'])))
            self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(data['name']))
            self.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(data['time']))
            self.listViewBtn[row].setEnabled(True)
            self.listDelBtn[row].setEnabled(True)
        if len(listShow) < 10:
            for row in range(len(listShow), 10):
                self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str('')))
                self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str('')))
                self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(str('')))
                self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(str('')))
                self.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(str('')))
                self.listViewBtn[row].setEnabled(False)
                self.listDelBtn[row].setEnabled(False)
        self.spinBox.setValue(pageNum)
        numberPage = math.ceil(len(self.jsonFiles) / 10)
        self.spinBox.setMaximum(max(numberPage-1,0))
        self.current_page = max(pageNum,0)

    def delItem(self, pos):
        os.remove(self.jsonFiles[pos])
        del self.jsonFiles[pos]
        numberPage = math.ceil(len(self.jsonFiles) / 10)
        futurePage = self.current_page if self.current_page <= numberPage-1 else numberPage-1
        futurePage = max(futurePage, 0)
        self.current_page = futurePage
        self.goPage(self.current_page)


    def UpdateItem(self):
        name = self.uiForm.NameEdit.text()
        age = self.uiForm.AgeEdit.value()
        genderG = self.uiForm.FemaleEdit.isChecked()
        genderM = self.uiForm.MaleEdit.isChecked()
        patientDesc = self.uiForm.DiseaseDescEdit.toPlainText()
        recorder = self.uiForm.RecorderEdit.text()
        location = self.uiForm.LocateEdit.text()
        recPlan = self.uiForm.RecPlanEdit.value()
        timeTmp = self.uiForm.dateTimeEdit.dateTime()
        time_string = timeTmp.toString(self.uiForm.dateTimeEdit.displayFormat())
        # check avalibale
        missingValue = False
        if name == '' or patientDesc == '' or recorder == '' or location == '':
            missingValue = True
        elif not genderG and not genderM : 
            missingValue = True
        elif age == 0 or recPlan == 0:
            missingValue = True
        if not missingValue:
            gender = "M"
            if genderG:
                gender = "Fm"
            # get ID 
            recordID = self.viewData['id']
            js = {
            'id': recordID,
            'name' : name, 
            'age' : age, 
            'gender': gender, 
            'patientDesc': patientDesc, 
            'recorder' : recorder, 
            'location' : location, 
            'recPlan' : recPlan, 
            'time' : time_string
            }
            fileName = './dataVIN/data' + str(recordID) + '.json'
            with open(fileName, 'w') as outfile:
                json.dump(js, outfile)
            self.Form.close()
            self.refreshPage(math.ceil(len(self.jsonFiles) / 10)-1)
        else:
            self.showErrorPopup("Please complete fully the form")

    def choosedInMsgUpdate(self, i):
        if i.text() == "OK":
            self.UpdateItem()

    
    def showChooseUpdate(self, error, pos):
        msg  = QtWidgets.QMessageBox()
        msg.setText(str(error) + str(self.jsonFiles[pos]))
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok | QtWidgets.QMessageBox.Cancel)
        msg.buttonClicked.connect(self.choosedInMsgUpdate)
        x = msg.exec_()


    def viewFunction(self, pos):
        file = self.jsonFiles[pos]
        with open(file) as json_file:
            data = json.load(json_file)
        self.viewData = data
        self.Form = QtWidgets.QWidget()
        self.uiForm = Ui_Form()
        self.uiForm.setupUi(self.Form)
        self.uiForm.extendSize(self.Form)

        self.uiForm.LoadBtn.setText("Sửa ?")
        self.uiForm.SaveBtn.hide()

        self.uiForm.NameEdit.setText(data['name'])
        self.uiForm.AgeEdit.setValue(data['age'])
        if data['gender'] == 'M':
            self.uiForm.MaleEdit.setChecked(True)
        else:
            self.uiForm.FemaleEdit.setChecked(True)
        self.uiForm.DiseaseDescEdit.setText(data['patientDesc'])
        self.uiForm.RecorderEdit.setText(data['recorder'])
        self.uiForm.LocateEdit.setText(data['location'])
        self.uiForm.RecPlanEdit.setValue(data['recPlan'])
        dataTime = QtCore.QDateTime.fromString(data['time'], 'd/M/yyyy hh:mm')
        self.uiForm.dateTimeEdit.setDateTime(dataTime)
        listEditatble = [self.uiForm.NameEdit, self.uiForm.AgeEdit, self.uiForm.MaleEdit, self.uiForm.FemaleEdit, self.uiForm.DiseaseDescEdit, 
            self.uiForm.RecorderEdit, self.uiForm.LocateEdit, self.uiForm.RecPlanEdit, self.uiForm.dateTimeEdit]
        for x in listEditatble:
            x.setEnabled(False)

        self.currentUpdate = False
        self.uiForm.LoadBtn.clicked.connect(lambda: self.enableEdit(listEditatble, pos))
        # load gif
        self.Form.show()

    def enableEdit(self, listEdit, pos):
        if not self.currentUpdate:
            for x in listEdit:
                x.setEnabled(True)
            self.uiForm.LoadBtn.setText("Sửa ?")
        else:
            for x in listEdit:
                x.setEnabled(False)
            self.uiForm.LoadBtn.setText("Cập nhật ?")
            self.showChooseUpdate("Do you want to update: ", pos)

        self.currentUpdate = not self.currentUpdate

    def turnOnSignal(self):
        self.Signal1.setChecked(False)
        # TODO #######################################################################

    def center(self):        
        frameGm = self.abc.frameGeometry()
        centerP = QtWidgets.QDesktopWidget().availableGeometry().center()
        frameGm.moveCenter(centerP)
        self.abc.move(frameGm.topLeft())

def readData(link = "./DataVIN/", prefixName = "Data"):
    if os.path.isdir(link):
        onlyfiles = [f for f in os.listdir(link) if os.path.isfile(link+f)]
        jsonFiles = [link+x for x in onlyfiles if x[-4:] == 'json']
        # print(jsonFiles)
    else:
        print("imported link is not exist")
        print("DataVIN folder is created, run again!")
        os.mkdir(link)
        onlyfiles = [f for f in os.listdir(link) if os.path.isfile(link+f)]
        jsonFiles = [link+x for x in onlyfiles if x[-4:] == 'json']
        # print(jsonFiles)
    return jsonFiles



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
