# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from createSub import createSub_Dialog
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import random


class Ui_MainWindow(QMainWindow):
    def __init__(self, parent=None):
        """Initializer."""
        super().__init__(parent)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1494, 866)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1481, 571))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.subjectWidget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.subjectWidget.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.subjectWidget.setObjectName("subjectWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.subjectWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 50, 481, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addLayout(self.gridLayout)
        # spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prevSub = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.prevSub.setObjectName("prevSub")
        self.horizontalLayout_2.addWidget(self.prevSub)
        self.nextSub = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.nextSub.setObjectName("nextSub")
        self.horizontalLayout_2.addWidget(self.nextSub)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.newSub = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.newSub.setObjectName("newSub")
        self.horizontalLayout_2.addWidget(self.newSub)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.subjectWidget)
        self.sampleWidget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.sampleWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sampleWidget.setObjectName("sampleWidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.sampleWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 60, 481, 251))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalSample = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalSample.setContentsMargins(0, 0, 0, 0)
        self.verticalSample.setObjectName("verticalSample")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.verticalSample.addWidget(self.label_2)
        self.gridLayout_sample = QtWidgets.QGridLayout()
        self.gridLayout_sample.setObjectName("gridLayout_sample")
        self.verticalSample.addLayout(self.gridLayout_sample)
        # spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.verticalSample.addItem(spacerItem2)
        self.horizontalLayout_sample = QtWidgets.QHBoxLayout()
        self.horizontalLayout_sample.setObjectName("horizontalLayout_sample")
        self.prevSam = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.prevSam.setObjectName("prevSam")
        self.horizontalLayout_sample.addWidget(self.prevSam)
        self.nextSam = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.nextSam.setObjectName("nextSam")
        self.horizontalLayout_sample.addWidget(self.nextSam)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_sample.addItem(spacerItem3)
        self.newSam = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.newSam.setObjectName("newSam")
        self.horizontalLayout_sample.addWidget(self.newSam)
        self.verticalSample.addLayout(self.horizontalLayout_sample)
        self.horizontalLayout.addWidget(self.sampleWidget)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(470, 610, 91, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1494, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.subjectWidget.setLayout(self.verticalLayout)
        self.sampleWidget.setLayout(self.verticalSample)

        self.createEvent()

    def createEvent(self):
        self.listSub = []
        self.listDirSub = readStorageData()
        self.currentPage = 0
        counter = 0
        # numSub = self.collectID(0)
        showDir = self.listDirSub[self.currentPage * 16:self.currentPage * 16 + 16]
        for x in range(4):
            for y in range(4):
                newSubject = QtWidgets.QWidget()
                newSubject.setObjectName("newSubject" + str(x) + str(y))
                subInfo = QtWidgets.QVBoxLayout(newSubject)
                subInfo.setContentsMargins(0, 0, 0, 0)
                subInfo.setObjectName("subInfo" + str(x) + str(y))
                subBtn = QtWidgets.QPushButton(newSubject)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(subBtn.sizePolicy().hasHeightForWidth())
                subBtn.setSizePolicy(sizePolicy)
                subBtn.setStyleSheet("background-color: rgba(255,255,255,0);border: 0px;")
                subBtn.setText("")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("folder-blue-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                subBtn.setIcon(icon)
                subBtn.setIconSize(QtCore.QSize(50, 50))
                subBtn.setObjectName("subBtn" + str(x) + str(y))
                subInfo.addWidget(subBtn)
                subLabel = QtWidgets.QLabel(newSubject)
                subLabel.setObjectName("subLabel" + str(x) + str(y))
                subLabel.setText("")
                subInfo.addWidget(subLabel, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
                subInfo.setStretch(0, 4)
                subInfo.setStretch(1, 1)
                subDict = {
                    'subject': newSubject,
                    'Info': subInfo,
                    'Btn': subBtn,
                    'Label': subLabel,
                    'pos': [x, y],
                    'dir': ""
                }
                self.listSub.append(subDict)
                self.gridLayout.addWidget(newSubject, x, y)
                if counter >= len(self.listDirSub):
                    newSubject.setEnabled(False)
                else:
                    subLabel.setText(str(showDir[counter]))
                    self.listSub[counter]['dir'] = showDir[counter]
                counter += 1

        for x in self.listSub:
            x['Btn'].clicked.connect(self.updateSamVisual(x))

        self.updateSam()

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        widget = QtWidgets.QWidget()
        widget.setLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(widget)
        self.newSam.clicked.connect(self.newSample)
        self.newSub.clicked.connect(self.newSubject)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HMIlab"))
        self.label.setText(_translate("MainWindow", "Danh sách người bệnh"))
        self.prevSub.setText(_translate("MainWindow", "Previous"))
        self.nextSub.setText(_translate("MainWindow", "Next"))
        self.newSub.setText(_translate("MainWindow", "New"))
        self.label_2.setText(_translate("MainWindow", "Danh sách bản ghi"))
        self.prevSam.setText(_translate("MainWindow", "Previous"))
        self.nextSam.setText(_translate("MainWindow", "Next"))
        self.newSam.setText(_translate("MainWindow", "New"))
        # self.nameSubject.setText(_translate("MainWindow", "Người bệnh + ID"))
        # self.nameSample.setText(_translate("MainWindow", "Tên file"))

    def collectID(self, page=0):
        return 0

    def newSubject(self):
        self.createSubdialog = createSub(self)
        self.createSubdialog.ui.saveBtn.clicked.connect(self.eventToDo)
        self.createSubdialog.exec_()

    def eventToDo(self):
        name = self.createSubdialog.ui.NameEdit.text()
        age = self.createSubdialog.ui.AgeEdit.value()
        genderG = self.createSubdialog.ui.FemaleEdit.isChecked()
        genderM = self.createSubdialog.ui.MaleEdit.isChecked()
        patientDesc = self.createSubdialog.ui.DiseaseDescEdit.toPlainText()
        patientStt = self.createSubdialog.ui.spinBox.text()

        missingValue = False
        if name == '' or patientDesc == '' or patientStt == '':
            missingValue = True
        elif not genderG and not genderM:
            missingValue = True
        elif age == 0:
            missingValue = True

        if not missingValue:
            print("full")
            gender = "M"
            if genderG:
                gender = "Fm"
            # get ID
            # id = last json number files
            recordID = random.randint(1, 100)
            js = {
                'id': recordID,
                'name': name,
                'age': age,
                'gender': gender,
                'patientDesc': patientDesc,
                'patientStt': patientStt,
            }
            newlink = './dataVIN/' + "_" + str(name) + "_" + str(recordID)
            os.mkdir(newlink)
            fileName = newlink + '/' + 'info.json'
            self.jsonFiles.append(fileName)
            with open(fileName, 'w') as outfile:
                json.dump(js, outfile)
            self.createSubdialog.close()
            # self.refreshPage(math.ceil(len(self.jsonFiles) / 10) - 1)
            # if self.loadingStt:
            #     self.stopLoadingFunc()
        else:
            self.showErrorPopup("Please complete fully the form")

    def newSample(self):
        print("newSam")

    def updateSam(self, listDir=[], page=0):
        self.listDirSam = listDir
        self.currentSamPage = page
        showDirSam = self.listDirSam[self.currentSamPage * 16:self.currentSamPage * 16 + 16]
        counter = 0
        # newSam = QtWidgets.QWidget()

        for x in range(4):
            for y in range(4):
                newSam = QtWidgets.QWidget()
                newSam.setObjectName("newSample" + str(x) + str(y))
                samInfo = QtWidgets.QVBoxLayout(newSam)
                samInfo.setContentsMargins(0, 0, 0, 0)
                samInfo.setObjectName("samInfo" + str(x) + str(y))
                samBtn = QtWidgets.QPushButton(newSam)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(samBtn.sizePolicy().hasHeightForWidth())
                samBtn.setSizePolicy(sizePolicy)
                samBtn.setStyleSheet("background-color: rgba(255,255,255,0);border: 0px;")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap("mfiles.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                icon2 = QtGui.QIcon()
                icon2.addPixmap(QtGui.QPixmap("file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                samBtn.setIcon(icon1)
                samBtn.setIconSize(QtCore.QSize(50, 50))
                samBtn.setObjectName("samBtn" + str(x) + str(y))
                samInfo.addWidget(samBtn)
                samLabel = QtWidgets.QLabel(newSam)
                samLabel.setObjectName("samLabel" + str(x) + str(y))
                samLabel.setText("")
                samInfo.addWidget(samLabel, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
                samInfo.setStretch(0, 4)
                samInfo.setStretch(1, 1)
                self.gridLayout_sample.addWidget(newSam, x, y)
                if counter >= len(showDirSam):
                    newSam.setEnabled(False)
                    samBtn.setIcon(icon2)
                else:
                    samLabel.setText(str(showDirSam[counter]))
                counter += 1

    def updateSamVisual(self, arg):
        def wrap():
            print("Updating Sam")
            print(arg['dir'])
            link = arg['dir']
            if os.path.isdir(link):
                onlydir = [link + "/" + d for d in os.listdir(link) if os.path.isdir(link + "/" + d)]
                print(onlydir)
            else:
                print("Error in link Sub")
            onlydir.sort(key=os.path.getctime)
            self.updateSam(listDir=onlydir)
            # print(arg[-1], arg[-2])
        return wrap

    def showErrorPopup(self, error):
        msg = QtWidgets.QMessageBox()
        msg.setText(str(error))
        x = msg.exec_()


def readStorageData(link="./DataVIN/"):
    if os.path.isdir(link):
        onlydir = [link + d for d in os.listdir(link) if os.path.isdir(link + d)]
    else:
        print("imported link is not exist")
        print("DataVIN folder is created, run again!")
        os.mkdir(link)
    onlydir.sort(key=os.path.getctime)
    return onlydir


class createSub(QDialog):
    """Employee dialog."""

    def __init__(self, parent=None):
        super().__init__(parent)
        # Create an instance of the GUI
        self.ui = createSub_Dialog()
        # Run the .setupUi() method to show the GUI
        self.ui.setupUi(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
